import ImageMapper from "react-img-mapper";
import * as data from "../data/data";
import image from "../images/download.png";
import { memo } from "react";

const MAX_TARGET = 3;

function IB({ targetSelection, targets, fillColorNotChosen, imageWidth }) {
  const lineWidth = 1;
  const strokeColor = "black";
  var MAP = {
    name: "bodymap",
    areas: [
      {
        id: "Head",
        title: "Head",
        shape: "poly",
        name: "Head",
        coords: [
          96, 22, 105, 10, 126, 6, 138, 17, 139, 30, 144, 37, 139, 50, 130, 66,
          104, 66, 96, 47, 92, 37, 98, 28, 96, 27, 96, 25,
        ],
      },
      {
        id: "RightShoulder",
        title: "RightShoulder",
        shape: "poly",
        name: "RightShoulder",
        coords: [101, 72, 75, 81, 66, 92, 62, 103, 101, 103],
      },
      {
        id: "LeftShoulder",
        title: "LeftShoulder",
        shape: "poly",
        name: "LeftShoulder",
        coords: [134, 73, 156, 81, 165, 87, 169, 102, 134, 102],
      },
      {
        id: "RightElbow",
        title: "RightElbow",
        shape: "poly",
        name: "RightElbow",
        coords: [58, 137, 78, 145, 69, 163, 50, 151],
      },
      {
        id: "LeftElbow",
        title: "LeftElbow",
        shape: "poly",
        name: "LeftElbow",
        coords: [153, 144, 158, 161, 181, 154, 173, 141, 174, 137],
      },
      {
        id: "RightWrist",
        title: "RightWrist",
        shape: "poly",
        name: "RightWrist",
        coords: [36, 180, 49, 190, 57, 181, 42, 169],
      },
      {
        id: "LeftWrist",
        title: "LeftWrist",
        shape: "poly",
        name: "LeftWrist",
        coords: [194, 184, 189, 172, 171, 182, 178, 195],
      },
      {
        id: "RightHand",
        title: "RightHand",
        shape: "poly",
        name: "RightHand",
        coords: [17, 193, 38, 216, 46, 203, 30, 186],
      },
      {
        id: "LeftHand",
        title: "LeftHand",
        shape: "poly",
        name: "LeftHand",
        coords: [210, 196, 188, 221, 182, 207, 201, 190, 209, 193],
      },
      {
        id: "RightHip",
        title: "RightHip",
        shape: "poly",
        name: "RightHip",
        coords: [74, 213, 108, 226, 106, 249, 74, 240],
      },
      {
        id: "LeftHip",
        title: "LeftHip",
        shape: "poly",
        name: "LeftHip",
        coords: [115, 225, 118, 248, 150, 242, 154, 215],
      },
      {
        id: "RightKnee",
        title: "RightKnee",
        shape: "poly",
        name: "RightKnee",
        coords: [99, 288, 76, 283, 72, 298, 99, 301],
      },
      {
        id: "LeftKnee",
        title: "LeftKnee",
        shape: "poly",
        name: "LeftKnee",
        coords: [125, 286, 126, 299, 152, 298, 148, 285],
      },
      {
        id: "RightAnkle",
        title: "RightAnkle",
        shape: "poly",
        name: "RightAnkle",
        coords: [76, 348, 95, 349, 94, 363, 76, 362, 76, 348],
      },
      {
        id: "LeftAnkle",
        title: "LeftAnkle",
        shape: "poly",
        name: "LeftAnkle",
        coords: [130, 348, 130, 360, 148, 360, 148, 348],
      },
      {
        id: "RightFeet",
        title: "RightFeet",
        shape: "poly",
        name: "RightdFeet",
        coords: [86, 397, 72, 386, 70, 375, 95, 381, 91, 389],
      },
      {
        id: "LeftFeet",
        title: "LeftFeet",
        shape: "poly",
        name: "LeftdFeet",
        coords: [140, 397, 153, 390, 155, 378, 133, 382],
      },
    ],
  };
  for (let i = 0; i < MAP["areas"].length; i++) {
    if (targets.includes(i)) {
      MAP["areas"][i]["preFillColor"] = data.colorMapping[i];
    } else {
      MAP["areas"][i]["preFillColor"] = fillColorNotChosen;

      if (targets.length === MAX_TARGET) {
        MAP["areas"][i]["disabled"] = true;
      }
    }
  }

  return (
    <ImageMapper
      width={imageWidth}
      imgWidth={221}
      src={image}
      map={MAP}
      onClick={(area) => targetSelection(area.id)}
      stayHighlighted
      strokeColor={strokeColor}
      lineWidth={lineWidth}
    />
  );
}

function arePropsEqual(prevProps, nextProps) {
  let t1 = prevProps.targets.sort();
  let t2 = nextProps.targets.sort();
  if (t1.length !== t2.length) return false;
  for (let i = 0; i < t1.length; i++) {
    if (t1[i] !== t2[i]) {
      return false;
    }
  }
  return true;
}

const ImageBody = memo(IB, arePropsEqual);
export default ImageBody;

{
  /*
    <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="download.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Head" title="Head" href="" coords="96,22,105,10,126,6,138,17,139,30,144,37,139,50,130,66,104,66,96,47,92,37,98,28,96,27,96,25" shape="poly">
    <area target="" alt="RightShoulder" title="RightShoulder" href="" coords="101,72,75,81,66,92,62,103,101,103" shape="poly">
    <area target="" alt="LeftShoulder" title="LeftShoulder" href="" coords="134,73,156,81,165,87,169,102,134,102" shape="poly">
    <area target="" alt="RightElbow" title="RightElbow" href="" coords="58,137,78,145,69,163,50,151" shape="poly">
    <area target="" alt="LeftElbow" title="LeftElbow" href="" coords="153,144,158,161,181,154,173,141,174,137" shape="poly">
    <area target="" alt="RightWrist" title="RightWrist" href="" coords="36,180,49,190,57,181,42,169" shape="poly">
    <area target="" alt="LeftWrist" title="LeftWrist" href="" coords="194,184,189,172,171,182,178,195" shape="poly">
    <area target="" alt="RightHand" title="RightHand" href="" coords="17,193,38,216,46,203,30,186" shape="poly">
    <area target="" alt="LeftHand" title="LeftHand" href="" coords="210,196,188,221,182,207,201,190,209,193" shape="poly">
    <area target="" alt="RightHip" title="RightHip" href="" coords="74,213,108,226,106,249,74,240" shape="poly">
    <area target="" alt="LeftHip" title="LeftHip" href="" coords="115,225,118,248,150,242,154,215" shape="poly">
    <area target="" alt="RightKnee" title="RightKnee" href="" coords="99,288,76,283,72,298,99,301" shape="poly">
    <area target="" alt="LeftKnee" title="LeftKnee" href="" coords="125,286,126,299,152,298,148,285" shape="poly">
    <area target="" alt="RightAnkle" title="RightAnkle" href="" coords="76,348,95,349,94,363,76,362,76,348" shape="poly">
    <area target="" alt="LeftAnkle" title="LeftAnkle" href="" coords="130,348,130,360,148,360,148,348" shape="poly">
    <area target="" alt="RightFeet" title="RightFeet" href="" coords="86,397,72,386,70,375,95,381,91,389" shape="poly">
    <area target="" alt="LeftFeet" title="LeftFeet" href="" coords="140,397,153,390,155,378,133,382,133,382" shape="poly">
</map>
</map> */
}
